name: learn_uncertainty
channels:
- https://conda.anaconda.org/conda-forge
- https://repo.anaconda.com/pkgs/main
dependencies:
- pandas
- matplotlib
- traffic
- poetry
- pygplates
- pip:
    - torch
    - torchvision
    - torchaudio
    
